apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metabase
spec:
  replicas: 1
  serviceName: metabase
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:v0.36.3"
          imagePullPolicy: IfNotPresent
          env:
          - name: MB_JETTY_HOST
            value: "0.0.0.0"
          - name: MB_JETTY_PORT
            value: "3000"
          - name: JAVA_TIMEZONE
            value: UTC
          - name: MB_EMOJI_IN_LOGS
            value: "true"
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 30
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
  updateStrategy:
    type: RollingUpdate